### ISSUE TITLE
使用yolox训练报错

### ISSUE THREAD

**Issue by fanweiya** [iscyy/yoloair#11]
```
Traceback (most recent call last):
  File "/data/yolo/yoloair/train.py", line 690, in <module>
    main(opt)
  File "/data/yolo/yoloair/train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "/data/yolo/yoloair/train.py", line 253, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "/data/yolo/yoloair/utils/autoanchor.py", line 43, in check_anchors
    anchors = m.anchors.clone() * m.stride.to(m.anchors.device).view(-1, 1, 1)  # current anchors
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectX' object has no attribute 'anchors'

```
使用了noautoanchor后报下面的错误
```
raceback (most recent call last):
  File "/data/yolo/yoloair/train.py", line 690, in <module>
    main(opt)
  File "/data/yolo/yoloair/train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "/data/yolo/yoloair/train.py", line 368, in train
    loss, loss_items = compute_loss(pred, targets.to(device))
  File "/data/yolo/yoloair/utils/loss.py", line 524, in __call__
    num_fg, ) = self.det.get_losses(
  File "/data/yolo/yoloair/models/yolox.py", line 408, in get_losses
    fg_mask_inds = torch.cat(fg_mask_inds, 0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

```

**Comment by iscyy** [comment]
Which train command are you using?

**Comment by fanweiya** [comment]
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --master_port 50013 --nproc_per_node 4 train.py --imgsz 640 --batch 4 --epochs 300 --data B_tai --cfg configs/yolox/yolox-s.yaml --cache --multi-scale --name B_tai --exist-ok --device 0,1,2,3 --noautoanchor

**Comment by fanweiya** [comment]
```
f PyTorch 1.11 and will be removed in a future release. Use aminmax instead. This warning will only appear once per process. (Triggered internally at  ../aten/src/ATen/native/ReduceAllOps.cpp:30.)
  min_k, max_k = torch._aminmax(dynamic_ks)
     0/299    0.757G     4.927     4.855      0.45       159       320:   0%|  Reducer buckets have been rebuilt in this iteration.
     0/299    0.828G     4.732      2.88    0.4307       585       832:  94%|██Traceback (most recent call last):
  File "/data/yolo/yoloair/train.py", line 690, in <module>
    main(opt)
  File "/data/yolo/yoloair/train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "/data/yolo/yoloair/train.py", line 368, in train
    loss, loss_items = compute_loss(pred, targets.to(device))
  File "/data/yolo/yoloair/utils/loss.py", line 524, in __call__
    num_fg, ) = self.det.get_losses(
  File "/data/yolo/yoloair/models/yolox.py", line 408, in get_losses
    fg_mask_inds = torch.cat(fg_mask_inds, 0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1485181 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1485182 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1485186 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 1485183) of binary: /data/anaconda3/envs/YOLOU/bin/python
Traceback (most recent call last):
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/anaconda3/envs/YOLOU/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-08-19_16:10:04
  host      : alit-PowerEdge-T640
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1485183)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

**Comment by iscyy** [comment]
Not the same repo, thanks

**Comment by fanweiya** [comment]
@iscyy 请问这个是什么原因呢
