### ISSUE TITLE
ModuleNotFoundError: No module named 'models.Core2024.EMO'

### ISSUE THREAD

**Issue by yujie-yang** [iscyy/yoloair#186]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

Traceback (most recent call last):
  File "E:\pyDevelop\yoloair\train.py", line 43, in <module>
    from models.yolo import Model
  File "E:\pyDevelop\yoloair\models\yolo.py", line 32, in <module>
    from models.Core2024.EMO import C3_RMB, CSRMBC, C2f_RMB, CPNRMB, ReNLANRMB
ModuleNotFoundError: No module named 'models.Core2024.EMO'                                      
How to solve this problem? Thank you so much.

**Comment by arrafi-musabbir** [comment]
I'm facing the same issue:
```
/content/yoloair
Traceback (most recent call last):
  File "/content/yoloair/train.py", line 43, in <module>
    from models.yolo import Model
  File "/content/yoloair/models/yolo.py", line 32, in <module>
    from models.Core2024.EMO import C3_RMB, CSRMBC, C2f_RMB, CPNRMB, ReNLANRMB
ModuleNotFoundError: No module named 'models.Core2024.EMO'
```

**Comment by zcswdt** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.
> 
> ### Question
> Traceback (most recent call last): File "E:\pyDevelop\yoloair\train.py", line 43, in from models.yolo import Model File "E:\pyDevelop\yoloair\models\yolo.py", line 32, in from models.Core2024.EMO import C3_RMB, CSRMBC, C2f_RMB, CPNRMB, ReNLANRMB ModuleNotFoundError: No module named 'models.Core2024.EMO' How to solve this problem? Thank you so much.
> 
> ### Additional
> _No response_

have you solved?

**Comment by Phoenix2022go** [comment]
I have the same problem, how to solve it?

**Comment by wahahaha98** [comment]
> have you solved?

have you solved?？

**Comment by zcswdt** [comment]
> > have you solved?
> 
> have you solved?？

no,you?
