### ISSUE TITLE
models.Core2024.EMO

### ISSUE THREAD

**Issue by zcswdt** [iscyy/yoloair#187]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

python train.py --data coco128.yaml --cfg configs/yolov5/yolov5s.yaml
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    from models.yolo import Model
  File "/home/zcs/work/github/yoloair/models/yolo.py", line 32, in <module>
    from models.Core2024.EMO import C3_RMB, CSRMBC, C2f_RMB, CPNRMB, ReNLANRMB
ModuleNotFoundError: No module named 'models.Core2024.EMO'

**Comment by wahahaha98** [comment]
你找到这个文件了吗
